show_all:
  prefix: /redfish/v1/Systems/System.Embedded.1/Storage/RAID.Integrated.1-1
  recurse: 0
show_pr:
  prefix: TODO
  # property: PatrolReadState
  # recurse: True
show_cc:
  prefix: TODO
show_bbu:
  prefix: TODO
show_enc:
  # prefix: /redfish/v1/Systems/System.Embedded.1/Storage/RAID.Integrated.1-1
  prefix: /redfish/v1/Chassis/Enclosure.Internal.0-1:RAID.Integrated.1-1
  # recurse: 1
show_disks:
  prefix: /redfish/v1/Chassis/Enclosure.Internal.0-1:RAID.Integrated.1-1
  property: Drives
  recurse: 3
show_logical:
  prefix: /redfish/v1/Systems/System.Embedded.1/Storage/RAID.Integrated.1-1/Volumes
  recurse: 2
