show_all:
  prefix: /redfish/v1/Systems/System.Embedded.1/Storage/RAID.Integrated.1-1
  recurse: 2
  json_filters:
    - key: pcislot
      jq: Oem.Dell.DellController.PCISlot
    - key: patrolread
      jq: Oem.Dell.DellController.PatrolReadState
    - key: firmware_version
      jq: Oem.Dell.DellController.ControllerFirmwareVersion
    - key: controller_model
      jq: StorageControllers[0].Model
    - key: memsize
      jq: Oem.Dell.DellController.CacheSizeInMB
  report: |
    Adapter #: {pcislot}
    Adapter Name: {controller_model}
    Firmware Build Version: {firmware_version}
    Memory Size: {memsize}
    Patrol Read State: {patrolread}


show_pr:
  prefix: /redfish/v1/Systems/System.Embedded.1/Storage/RAID.Integrated.1-1
  json_filters:
    - key: pcislot
      jq: Oem.Dell.DellController.PCISlot
    - key: patrolread
      jq: Oem.Dell.DellController.PatrolReadState
  report: |

    Adapter #: {pcislot}
    Patrol Read State: {patrolread}

show_cc:
  prefix: /redfish/v1/Systems/System.Embedded.1/Storage/Volumes/Disk.Virtual.1:RAID.Integrated.1-1/Actions
  recurse: 1
show_bbu:
  prefix: TODO


show_enc:
#  prefix: /redfish/v1/Dell/Chassis/System.Embedded.1/DellEnclosureCollection
#  prefix: /redfish/v1/Chassis/Enclosure.Internal.0-1:RAID.Integrated.1-1
#  prefix: /redfish/v1/Dell/Chassis/System.Embedded.1/DellEnclosure/Enclosure.Internal.0-1:RAID.Integrated.1-1
  prefix: /redfish/v1/Chassis/Enclosure.Internal.0-1:RAID.Integrated.1-1
  json_filters:
    - key: connector
      jq: "Oem.Dell.DellEnclosure.Connector"
    - key: enclosure
      jq: "Description"
    - key: health
      jq: "Status.Health"
    - key: drivecount
      jq: "Links.\"Drives@odata.count\""
    - key: slotcount
      jq: "Oem.Dell.DellEnclosure.SlotCount"
##    - key: allenclosures
##      jq: "Members[*][?(Name == `DellEnclosure`)]{Id: Id, Status: Status.\"Health\", Drives: Links.\"Drives@odata.count\", }"
#    - key: enclosurecount
#      jq: "Links\"Members@odata.count\""
  report: |

    Adapter #: {connector}
    Enclosure: {enclosure}
    Status: {health}
    Slots: {slotcount}
    Drives: {drivecount}
#    Fans: 0
#    Power Supplies: 0
#    Temperature Sensors: 0

  recurse: 0

show_disks:
  prefix: /redfish/v1/Systems/System.Embedded.1/Storage/RAID.Integrated.1-1
#  prefix: /redfish/v1/Dell/Systems/System.Embedded.1/Storage/Drives/DellPhysicalDisk/Disk.Bay.6:Enclosure.Internal.0-1:RAID.Integrated.1-1
  json_filters:
    - key: alldrives
      jq: "Drives[*].{BlockSizeBytes: BlockSizeBytes, Revision: Revision, CapableSpeedGbs: CapableSpeedGbs, Manufacturer: Manufacturer, SerialNumber: SerialNumber, CapacityBytes: naturalsize(CapacityBytes), Model: Model, Name: Name }"
      format: |
       [{Name}]    ? ? ? ? {CapacityBytes} {Manufacturer} {SerialNumber} {Revision} : ?Configured(), Spun ?(UP/DOW)
    - key: drivecount
      jq: "\"Drives@odata.count\""
    - key: failingcount
      jq: "length(Drives[?(Status.Health != `OK`)])"
  report: |

    All Drives:
    {alldrives}

    There are {drivecount} drives:

    Failed or Rebuilding Disks:
    There are {failingcount} failing drives out of {drivecount}

  recurse: 1
show_logical:
  prefix: /redfish/v1/Systems/System.Embedded.1/Storage/RAID.Integrated.1-1/Volumes
  json_filters:
    - key: allvolumes
      jq: >
        Members[*].{
        Name: Oem.Dell.DellVirtualDisk.Id,
        VirtualDiskTargetID: Oem.Dell.DellVirtualDisk.VirtualDiskTargetID,
        DiskCachePolicy: Oem.Dell.DellVirtualDisk.DiskCachePolicy,
        ReadCachePolicy: Oem.Dell.DellVirtualDisk.ReadCachePolicy,
        WriteCachePolicy: Oem.Dell.DellVirtualDisk.WriteCachePolicy,
        SpanDepth: Oem.Dell.DellVirtualDisk.SpanDepth,
        SpanLength: Oem.Dell.DellVirtualDisk.SpanLength,
        Status: Status.Health
        MemberDisks: "@Redfish.Settings".SettingsObject.Links.Drives[*].{ BlockSizeBytes: BlockSizeBytes, Revision: Revision, CapableSpeedGbs: CapableSpeedGbs, Manufacturer: Manufacturer, SerialNumber: SerialNumber, CapacityBytes: naturalsize(CapacityBytes), Model: Model, Name: Name }
        }
      sub_formats:
        MemberDisks: |
          \t\t[{Name}] {CapacityBytes} {Manufacturer} {Model} {SerialNumber}

      format: |

        [{Name}]
          Virtual Drive: {VirtualDiskTargetID}
          Cache Policy: {DiskCachePolicy}
          Span Depth: {SpanDepth}
          Span Length: {SpanLength}

          Status: {Status}
          Members:
        {MemberDisks}
  report: |
    {allvolumes}
  recurse: 4
nagios:
  prefix: /redfish/v1/Systems/System.Embedded.1/Storage/RAID.Integrated.1-1
  recurse: 3
  json_filters:
    - key: drive_health
      jq: Oem.Dell.DellController.PCISlot
    - key: patrolread
      jq: Oem.Dell.DellController.PatrolReadState
    - key: firmware_version
      jq: Oem.Dell.DellController.ControllerFirmwareVersion
    - key: controller_model
      jq: StorageControllers[0].Model
    - key: memsize
      jq: Oem.Dell.DellController.CacheSizeInMB
  report: |
    Adapter #: {pcislot}
    Adapter Name: {controller_model}
    Firmware Build Version: {firmware_version}
    Memory Size: {memsize}
    Patrol Read State: {patrolread}