show_all:
  prefix: /redfish/v1/Systems/System.Embedded.1/Storage/RAID.Integrated.1-1
  # recurse: 0
  json_filters:
    - key: pcislot
      jq: Oem.Dell.DellController.PCISlot
    - key: patrolread
      jq: Oem.Dell.DellController.PatrolReadState
    - key: firmware_version
      jq: Oem.Dell.DellController.ControllerFirmwareVersion
    - key: controller_model
      jq: StorageControllers[0].Model
    - key: memsize
      jq: Oem.Dell.DellController.CacheSizeInMB
  report: |
    Adapter # {pcislot}
    Adapter Name: {controller_model}
    Firmware Build Version: {firmware_version}
    Memory Size: {memsize}
    Patrol Read State: {patrolread}


show_pr:
  prefix: TODO
  # recurse: True
show_cc:
  prefix: TODO
show_bbu:
  prefix: TODO
show_enc:
  # prefix: /redfish/v1/Systems/System.Embedded.1/Storage/RAID.Integrated.1-1
  prefix: /redfish/v1/Chassis/Enclosure.Internal.0-1:RAID.Integrated.1-1
  # recurse: 1
show_disks:
  prefix: /redfish/v1/Systems/System.Embedded.1/Storage/RAID.Integrated.1-1
  json_filters:
    - key: alldrives
      jq: "Drives[*].{BlockSizeBytes: BlockSizeBytes, Revision: Revision, CapableSpeedGbs: CapableSpeedGbs, Manufacturer: Manufacturer, SerialNumber: SerialNumber, CapacityBytes: naturalsize(CapacityBytes), Model: Model, Name: Name}"
      transforms:
        CapacityBytes: naturalsize
      # format: |
      #   [{Name}]    ? ? ? ? {CapacityBytes} {Manufacturer} {SerialNumber} {Revision} : ?Configured(), Spun ?(UP/DOW)
    - key: drivecount
      jq: "\"Drives@odata.count\""
    - key: failingcount
      jq: "length(Drives[?(Status.Health != `null`)])"
  # report: |
  #   All Drives:
  #   {alldrives}

  #   There ared {drivecount} drives:

  #   Failed or Rebuilding Disks:
  #   There are {failingcount} failing drives out of {drivecount}

#       BlockSizeBytes
# CapableSpeedGbs
# CapacityBytes
# Description
# Id
# Manufacturer
# MediaType
# Model
# Name
# NegotiatedSpeedGbs
# PartNumber
# PredictedMediaLifeLeftPercent
# Protocol
# Revision
# SerialNumber
# Status

# BlockSizeBytes
# CapableSpeedGbs
# CapacityBytes
# Description
# Id
# Manufacturer
# MediaType
# Model
# Name
# NegotiatedSpeedGbs
# PartNumber
# PredictedMediaLifeLeftPercent
# Protocol
# Revision
# SerialNumber
# Status
  recurse: 1
show_logical:
  prefix: /redfish/v1/Systems/System.Embedded.1/Storage/RAID.Integrated.1-1/Volumes
  recurse: 2
