show_all:
  prefix: /redfish/v1/Systems/1/SmartStorage/ArrayControllers/0
  json_queries:
    - result_key: first_item
      jq: /item[0]
  report_format: >
    This report shows the first item {first_item}
show_pr:
  prefix: TODO
  property: PatrolReadState
show_cc:
  prefix: TODO
  property: TODO
show_bbu:
  prefix: TODO
show_enc:
  prefix: /redfish/v1/Systems/1/SmartStorage/ArrayControllers/0/StorageEnclosures
  recurse: True
show_disks:
  prefix: /redfish/v1/Systems/1/SmartStorage/ArrayControllers/0/DiskDrives
  recurse: True
show_logical:
  prefix: /redfish/v1/Systems/1/SmartStorage/ArrayControllers/0/LogicalDrives
  recurse: True
nagios:
  prefix: /redfish/v1/Systems/1/SmartStorage/ArrayControllers/0