show_all:
  prefix: /redfish/v1/Systems/1/SmartStorage/ArrayControllers/0
  json_queries:
    - endpoint_regex: ArrayController
      queries:
        - result_key: TEST
          jq: /item[0]
show_pr:
  prefix: TODO
  property: PatrolReadState
show_cc:
  prefix: TODO
  property: TODO
show_bbu:
  prefix: TODO
show_enc:
  prefix: /redfish/v1/Systems/1/SmartStorage/ArrayControllers/0/StorageEnclosures
  recurse: True
show_disks:
  prefix: /redfish/v1/Systems/1/SmartStorage/ArrayControllers/0/DiskDrives
  recurse: True
show_logical:
  prefix: /redfish/v1/Systems/1/SmartStorage/ArrayControllers/0/LogicalDrives
  recurse: True
